### ISSUE TITLE
Are you planing to release FlickrStyle10K dataset?

### ISSUE THREAD

**Issue by hwijeen** [kacky24/stylenet#2]
Hi,
I'm a graduate student majoring NLP.

I came across your work recent, and I found it very interesting.
I thought I would implement your model(Factored LSTM), and to do so I would need your dataset.

It is written in the paper that you would release the data to community, but apparently it is not available at the moment.

Is there any chance you will release the dataset to the public?

Best 
Hwijeen

**Comment by kacky24** [comment]
Hello
I'm not an author and I don't have the right to share it.
I only implemented it from the paper.
When I implemented it, I asked authors to share the dataset.

Best Regards,
Kota Kakiuchi

**Comment by tingyaohsu** [comment]
Hi, 
I'm also a graduate student doing related research. I found your work and it's great. I would like to implement your model, but I still need the dataset.
If you already completed it, can you share the dataset?

Sincerely,
Tingyao

**Comment by kacky24** [comment]
Hello
Now authors share the dataset in https://zhegan27.github.io/Paper.html.
Best Regards,
Kota Kakiuchi
