### ISSUE TITLE
Generated sentences not related to images

### ISSUE THREAD

**Issue by tingyaohsu** [kacky24/stylenet#4]
Hi, 
sorry to bother you again.
I encountered the same problem as you when generating sentences . And I reimplemented each step by step but still couldn't find where the problem is.  If you already find the problem or possible reason, would you please let me know? Thanks a lot !

Sincerely,
Tingyao

**Comment by kacky24** [comment]
Hello,

I'm sorry, but I've not found the bug.
If I find it . i'll tell you.

Best Regards,
Kota Kakiuchi

**Comment by JunlongFeng** [comment]
I came into this problem because of the different  order of   images in the  first  and the second  training. The captions in 'funny_train.txt' and 'roman_train.txt' are corresponding to images (in train.p).So,
make sure that you have the same and correct images' order during  training.
