### ISSUE TITLE
State of the project?

### ISSUE THREAD

**Issue by samhumeau** [kacky24/stylenet#5]
Hi, thanks for the hard work!

I had some questions about the state of the code right now:
- Can you actually reproduce the results of the paper?
- Is there a pre-trained model available somewhere?

Best, 
Sam

**Comment by kacky24** [comment]
Hello

I'm sorry, but my code has a problem and my model usually generate sentences not related to images.
I want to modify it but I can't have enough time now.
If you find the problem, please let me know.

Best Regards,
Kota

**Comment by gorgeousyouth** [comment]
excuse me, do you modify the code ? Can you actually reproduce the results of the paper?

**Comment by kacky24** [comment]
Sorry, I've not modified it yet.
Now I don't have enough time and I don't understand what is wrong, so it may take much time.

**Comment by gorgeousyouth** [comment]
> Sorry, I've not modified it yet.
> Now I don't have enough time and I don't understand what is wrong, so it may take much time.

Thanks
